sudo: required
services:
  - docker
env:
  - NPM_TARGET=test
  - NPM_TARGET=lint
  - NPM_TARGET=coverage


before_install:
  - docker pull node:8-onbuild

Install:
  - docker build -t probot-hello .

Script:
  - docker run --rm probot-hello npm run $NPM_TARGET


After_success:
  - set -x -v;
    set -e
    if["${NPM_TARGET}" = "test" ] ; then
      docker tag probot-hello probot-hello:$(git rev-parse HEAD);
    else
     echo "skipping docker tag";
    fi;
    docker images;
    set +x +v;
